### ISSUE TITLE
Failed to start dewheater

### ISSUE THREAD

**Issue by Stewaro** [Curtis2012/dewheater#13]
Hi,
after installing and running >sudo systemctl status dewheater< the error is:

dewheater.service - dewheater
    Loaded: loaded (/lib/systemd/system/dewheater.service; enabled; vendor preset: enabled)
    Active: failed (Result: exit-code) since Mon 2023-02-06 16:30:34 CET; 32min ago
   Process: 688 ExecStart=/usr/bin/python3 /home/pi/dewheater/dewheater.py (code=exited, status=1/FAILU
  Main PID: 688 (code=exited, status=1/FAILURE)

Feb 06 16:30:34 allsky systemd[1]: dewheater.service: Service RestartSec=100ms expired, scheduling res
Feb 06 16:30:34 allsky systemd[1]: dewheater.service: Scheduled restart job, restart counter is at 5.
Feb 06 16:30:34 allsky systemd[1]: Stopped dewheater.
Feb 06 16:30:34 allsky systemd[1]: dewheater.service: Start request repeated too quickly.
Feb 06 16:30:34 allsky systemd[1]: dewheater.service: Failed with result 'exit-code'.
Feb 06 16:30:34 allsky systemd[1]: Failed to start dewheater.

Where is my mistake?

Greetings 
Henry

**Comment by Curtis2012** [comment]
Henry, this type of output is usually due to the service failing at the application level. My guess would be a configuration file issue.  In order to see what is actually happening you will need to capture the output of dewheater at the time of the crash.  See the journalctl command to do this.

https://linuxhint.com/linux-journalctl-command/

Post the journal output and a copy of your config file.

**Comment by Stewaro** [comment]
Hi Curtis2012,

thanks for the help!

Extract from journalctl:

Feb 06 18:17:38 allsky rpi-eeprom-update[400]:     LATEST: Di 25. Jan 14:30:41 UTC 2022 (1643121041)
Feb 06 18:17:38 allsky rpi-eeprom-update[400]:    RELEASE: default (/lib/firmware/raspberrypi/bootloader/default)
Feb 06 18:17:38 allsky rpi-eeprom-update[400]:             Use raspi-config to change the release.
Feb 06 18:17:38 allsky rpi-eeprom-update[400]:   VL805_FW: Dedicated VL805 EEPROM
Feb 06 18:17:38 allsky rpi-eeprom-update[400]:      VL805: up to date
Feb 06 18:17:38 allsky rpi-eeprom-update[400]:    CURRENT: 000138a1
Feb 06 18:17:38 allsky rpi-eeprom-update[400]:     LATEST: 000138a1
Feb 06 18:17:38 allsky systemd[1]: Started Check for Raspberry Pi EEPROM updates.
Feb 06 18:17:38 allsky vncserver-x11[559]: ConsoleDisplay: Cannot find a running X server on vt1
Feb 06 18:17:38 allsky vncserver-x11[559]: ConsoleDisplay: Found running X server (pid=590, binary=/usr/lib/xorg/Xor
Feb 06 18:17:38 allsky python3[411]: Traceback (most recent call last):
Feb 06 18:17:38 allsky python3[411]:   File "/home/pi/dewheater/dewheater.py", line 30, in <module>
Feb 06 18:17:38 allsky python3[411]:     import bme280
Feb 06 18:17:38 allsky python3[411]: ModuleNotFoundError: No module named 'bme280'
Feb 06 18:17:38 allsky systemd[1]: dewheater.service: Main process exited, code=exited, status=1/FAILURE
Feb 06 18:17:38 allsky systemd[1]: dewheater.service: Failed with result 'exit-code'.
Feb 06 18:17:38 allsky CRON[467]: (CRON) info (No MTA installed, discarding output)
Feb 06 18:17:38 allsky CRON[467]: pam_unix(cron:session): session closed for user pi
Feb 06 18:17:39 allsky systemd[1]: dewheater.service: Service RestartSec=100ms expired, scheduling restart.
Feb 06 18:17:39 allsky systemd[1]: dewheater.service: Scheduled restart job, restart counter is at 1.
Feb 06 18:17:39 allsky systemd[1]: Stopped dewheater.
Feb 06 18:17:39 allsky systemd[1]: Started dewheater.
Feb 06 18:17:39 allsky python3[677]: Traceback (most recent call last):
lines 579-601

config file: dewheaterconfig.json
{"debug": true,
  "sensorType": "DHT22",
  "dhtPin": 4,
  "bmePort": 1,
  "bmeAddress": "0x76",
  "dewHeaterPin": 25,
  "dewHeaterCutinOffset": 1.0,
  "dewHeaterCutoutOffset": 1.0,
  "dewHeaterMaxTemp": 30.0,
  "dewHeaterMinTemp": 1.0,
  "dewHeaterMaxTimeOn": 6.5,
  "dewHeaterOnOffDelay": 5,
  "dewPtCheckDelay": 5,
  "fakeDewPoint": false,
  "fakeDewPointSamples": 20,
  "invertOnOff": false}

Henry

**Comment by Curtis2012** [comment]
...
Feb 06 18:17:38 allsky python3[411]: ModuleNotFoundError: No module named 'bme280'
...


Looks like you need to install the 'bme280' module in your environment.

Which version of Python are you running?

**Comment by Curtis2012** [comment]
Did this fix work for you?

**Comment by Stewaro** [comment]
It does not work. Get no further.

----------------------------------------------------

Python 3.7.3 (/usr/bin/python3)
>>> %Run dewheater.py
{
    "bmeAddress": "0x76",
    "bmePort": 1,
    "debug": true,
    "dewHeaterCutinOffset": 1.0,
    "dewHeaterCutoutOffset": 1.0,
    "dewHeaterMaxTemp": 30.0,
    "dewHeaterMaxTimeOn": 6.5,
    "dewHeaterMinTemp": 1.0,
    "dewHeaterOnOffDelay": 5,
    "dewHeaterPin": 25,
    "dewPtCheckDelay": 5,
    "dhtPin": 4,
    "fakeDewPoint": false,
    "fakeDewPointSamples": 20,
    "invertOnOff": false,
    "sensorType": "DHT22"
}
Traceback (most recent call last):
  File "/home/pi/dewheater/dewheater.py", line 119, in <module>
    bme = BME820Class()
  File "/home/pi/dewheater/dewheater.py", line 110, in __init__
    self.bme_calibration_params = bme280.load_calibration_params(self.bus, self.address)
  File "/usr/local/lib/python3.7/dist-packages/bme280/__init__.py", line 154, in load_calibration_params
    compensation_params.dig_T1 = read.unsigned_short(0x88)
  File "/usr/local/lib/python3.7/dist-packages/bme280/reader.py", line 40, in unsigned_short
    return self._bus.read_word_data(self._address, register) & 0xffff
  File "/home/pi/.local/lib/python3.7/site-packages/smbus2/smbus2.py", line 474, in read_word_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error

**Comment by Curtis2012** [comment]
Odd. It appears that even though you have a DHT configured, it is still trying to read a BME.

Which branch did you download from?

**Comment by Curtis2012** [comment]
Looking at this again, it looks like your I2C bus may not be set up properly. Have you enabled I2C using raspi-config?

Also see installnotes.txt in the repository.

**Comment by Stewaro** [comment]
Python 3.7.3 (/usr/bin/python3)
>>> %Run dewheater.py
{
    "bmeAddress": "0x76",
    "bmePort": 1,
    "debug": true,
    "dewHeaterCutinOffset": 1.0,
    "dewHeaterCutoutOffset": 1.0,
    "dewHeaterMaxTemp": 30.0,
    "dewHeaterMaxTimeOn": 6.5,
    "dewHeaterMinTemp": 1.0,
    "dewHeaterOnOffDelay": 5,
    "dewHeaterPin": 25,
    "dewPtCheckDelay": 5,
    "dhtPin": 4,
    "fakeDewPoint": false,
    "fakeDewPointSamples": 20,
    "invertOnOff": false,
    "sensorType": "DHT22"
}
Traceback (most recent call last):
  File "/home/pi/dewheater/dewheater.py", line 119, in <module>
    bme = BME820Class()
  File "/home/pi/dewheater/dewheater.py", line 110, in __init__
    self.bme_calibration_params = bme280.load_calibration_params(self.bus, self.address)
  File "/usr/local/lib/python3.7/dist-packages/bme280/__init__.py", line 154, in load_calibration_params
    compensation_params.dig_T1 = read.unsigned_short(0x88)
  File "/usr/local/lib/python3.7/dist-packages/bme280/reader.py", line 40, in unsigned_short
    return self._bus.read_word_data(self._address, register) & 0xffff
  File "/home/pi/.local/lib/python3.7/site-packages/smbus2/smbus2.py", line 474, in read_word_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
>>> 

Python 3.7.3 (/usr/bin/python3)
##############################
I2C with raspi-config is enabled. I'm not a Linux professional or a programmer

**Comment by Curtis2012** [comment]
@Stewaro 

Did you get this running?

**Comment by Curtis2012** [comment]
No response so I'm closing this issue. Please post again if unresolved.
