### ISSUE TITLE
Adafruit

### ISSUE THREAD

**Issue by Dentonknifeworks** [Curtis2012/dewheater#3]
ModuleNotFoundError: No module named 'Adafruit_DHT'

I have installed the Adafruit libraries and still get this error.
Tried so many links to install and still get the run error.
I do have paython3 installed and using it as a command line.
What is a good link-command to get the correct libraries?
Thanks
Brad

**Comment by Dentonknifeworks** [comment]
I have tried bullseye and buster.
Brad

**Comment by Curtis2012** [comment]
I'm back now and looking at this. I have an extra RPi 3B+. I will make a clean install on it and see if I can reproduce the problem.

**Comment by Curtis2012** [comment]
Brad,

I created a fresh install of Raspian Buster on an Rpi 3B+ and began installing the dewheater service. 

I created a directory under $HOME named "dewheater" and copied the source code to there.

I ran "dewheater.py" from that directory to see what imports would fail initially.  Conveniently, the first import fail was for was for Adafruit_DHT. 

I followed the installation instructions for Adafruit_DHT at the following link and this resolved the import failure. 

https://learn.adafruit.com/adafruit-io-basics-temperature-and-humidity/python-setup

Please confirm whether this works for you.

**Comment by Dentonknifeworks** [comment]
Doing this on Bullseye

sudo pip3 install Adafruit_DHT. I get the Errors Below.

Going to try Buster next but I think I have seen this error on it also.

ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-arsxpf2u/adafruit-dht_01db9162c57047a78f6ba301e99dc0db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-arsxpf2u/adafruit-dht_01db9162c57047a78f6ba301e99dc0db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-odqyjq_2
       cwd: /tmp/pip-install-arsxpf2u/adafruit-dht_01db9162c57047a78f6ba301e99dc0db/
  Complete output (1 lines):
  Could not detect if running on the Raspberry Pi or Beaglebone Black.  If this failure is unexpected, you can run again with --force-pi or --force-bbb parameter to force using the Raspberry Pi or Beaglebone Black respectively.
  ----------------------------------------
  ERROR: Failed building wheel for Adafruit-DHT
  Running setup.py clean for Adafruit-DHT
Failed to build Adafruit-DHT
Installing collected packages: Adafruit-DHT
    Running setup.py install for Adafruit-DHT ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-arsxpf2u/adafruit-dht_01db9162c57047a78f6ba301e99dc0db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-arsxpf2u/adafruit-dht_01db9162c57047a78f6ba301e99dc0db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m64927l3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/Adafruit-DHT
         cwd: /tmp/pip-install-arsxpf2u/adafruit-dht_01db9162c57047a78f6ba301e99dc0db/
    Complete output (1 lines):
    Could not detect if running on the Raspberry Pi or Beaglebone Black.  If this failure is unexpected, you can run again with --force-pi or --force-bbb parameter to force using the Raspberry Pi or Beaglebone Black respectively.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-arsxpf2u/adafruit-dht_01db9162c57047a78f6ba301e99dc0db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-arsxpf2u/adafruit-dht_01db9162c57047a78f6ba301e99dc0db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m64927l3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/Adafruit-DHT Check the logs for full command output.

**Comment by Dentonknifeworks** [comment]
Well On buster got past the first error
Now seeing
ImportError: cannot import name 'Beaglebone_Black_Driver' from 'Adafruit_DHT' (/usr/local/lib/python3.7/dist-packages/Adafruit_DHT/__init__.py)

Looking into that now.
Brad

**Comment by Curtis2012** [comment]
Brad,

Looks like to me that the library install issue is just a symptom of something lower level. 

What physical board are you actually running?

**Comment by Dentonknifeworks** [comment]
I got it working doing this In "/usr/local/lib/python3.7/dist-packages/Adafruit_DHT/platform_detect.py", you can add the followings at line #112 in the elif ladder, so it should workaround the issue.

elif match.group(1) == 'BCM2711':
    return 3
It looks like the hardware name in the /proc/cpuinfo has been changed due to the recent raspbian upgrade.

This is a pi 4 compute module but I had the same issues on a Pi4 4gb. 
I also had to install Metecalc using pip3 install meteocalc

**Comment by Dentonknifeworks** [comment]
So this was the workflow to get it working on Buster and a pi 4 Comput Module.

sudo apt-get update
 
sudo apt-get upgrade
 
and
 
sudo pip3 install --upgrade setuptools
 
sudo pip3 install Adafruit_DHT
 
pip3 install adafruit-io
 
pip3 install meteocalc
Edit
"/usr/local/lib/python3.7/dist-packages/Adafruit_DHT/platform_detect.py", you can add the following at line #112 in the elif ladder, so it should work around the issue.
 
elif match.group(1) == 'BCM2711':
return 3

**Comment by Curtis2012** [comment]
Good timing, I was just working on install instructions. As a result I had already run into the "pip3" requirement for meteocalc. I am revising my notes to use pip3 and python3 throughout. 

I assume the error messages referencing "BeagleBone" were just a result of erroneous platform ID. 

Thanks for posting the details!

**Comment by Curtis2012** [comment]
@Dentonknifeworks

Below are my rough notes made while creating a fresh install on a RPi 3B+. 

I will revise based on your posts above. 

I will refine these notes a bit and add them to the repository.

Please review and let me know if any suggestions.

Dew Heater Service Install

 1  The following instructions were created by installing dewheater on a fresh install of Raspian Buster.

 2  Install source code
 2.1  mkdir dewheater below $HOME
 2.2  Copy the following files to dewheater directory

		dewheaterconfig.json
		dewheateron.py
		dewheater.service
		dewheateroff.py
		dewheater.py
		dewheatertest.py

 3  Install libraries
 3.1  sudo apt update
 3.2  sudo apt upgrade
 3.3  This installation assumes you are using python3 and pip3
 3.4  Adafruit_DHT
 3.4.1  Follow instructions at this link:

	https://learn.adafruit.com/adafruit-io-basics-temperature-and-humidity/python-setup

 3.5  meteocalc
 3.5.1  sudo pip3 install meteocalc 
 3.5.1.1  note that “pip” may not function properly, use pip3.
 3.6  Other libraries referenced (sys, json, GPIO, and time) should not require an explicit install

 4  Configure Service
 4.1  Copy dewheater.service from dewheater directory to /lib/systemd/system/
 4.1.1  sudo cp /home/pi/dewheater/dewheater.service /lib/systemd/system/
 4.2  Start dewheater service
 4.2.1  sudo systemctl start dewheater
 4.3  Enable dewheater service to start at boot
 4.3.1  sudo systemctl enable dewheater
 4.4  Check status of dewheater service
 4.4.1   sudo systemctl status dewheater
 4.4.2  Example output

● dewheater.service - dewheater
   		Loaded: loaded (/lib/systemd/system/dewheater.service; disabled; vendor preset: enabled)
   		Active: active (running) since Fri 2022-01-21 17:44:20 PST; 6s ago
 		Main PID: 30059 (python3)
    		Tasks: 1 (limit: 2062)
   		CGroup: /system.slice/dewheater.service
           			└─30059 /usr/bin/python3 /home/pi/dewheater/dewheater.py

**Comment by Dentonknifeworks** [comment]
I connected the Relay and the dewheatertest.py was not turning on and off the relay.
I changed the code from GPIO.setmode(GPIO.BCM) to GPIO.setmode(GPIO.BOARD).
I did this in all of the scripts that had GPIO.BCM
Now I need to put it outside and test it.

**Comment by Curtis2012** [comment]
Interesting. BCM mode works on my configuration. I will test it on my new install also.

How did you set the pin numbers in the config file? Did you assume BCM or BOARD?

Are you running the latest code?

**Comment by Dentonknifeworks** [comment]
No charges to the Jason file I hooked it up according to it. Downloaded the code yesterday.

**Comment by Curtis2012** [comment]
Which physical pins did you connect to on the board?

**Comment by Dentonknifeworks** [comment]
Pin 4 and pin 23.

**Comment by Dentonknifeworks** [comment]
Thanks for the help looks like things are working at this time.
Closing
Brad

**Comment by Curtis2012** [comment]
Good, glad you are up and running. 

I will take a look at the pin issue for future reference.
